---
#
  - name: Stop firewalld
    service: name=firewalld state=stopped enabled=no
    ignore_errors: True

  - name: Stop iptables
    service: name=iptables state=stopped enabled=no
    ignore_errors: True
