---
  - name: installing ansible application requiriments
    yum: name={{ item }} state=installed
    with_items:
    - epel-release

  - name: upgrade all packages
    yum: name='*' state=latest

  - name: installing ansible application requiriments
    yum: name={{ item }} state=installed
    with_items:     
    - libselinux-python
    - python-pip
    - python
    - python-devel
    - yum-utils 
    - device-mapper-persistent-data 
    - lvm2
    - nfs-utils

  - name: Installing Docker Repo
    command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    ignore_errors: True

  - name: installing ansible application requiriments
    yum: name={{ item }} state=installed
    with_items:
    - docker-ce

  - name: starting services and enabling
    service: name={{ item }} state=restarted enabled=yes
    with_items:  
    - docker
   
